### ISSUE TITLE
无法打开相机

### ISSUE THREAD

**Issue by ydy2021** [Cuirongcheng/Image-matching-and-ranging-based-on-binocular-stereo-vision#4]
我无法打开相机，提示没有找到相机，请确认连接和相机IP设置，怎么设置呢？

**Comment by aaronrgqw** [comment]
这个是啥原因啊E:\python\python.exe C:/Users/18776/Desktop/毕业设计/源代码/index.py
Traceback (most recent call last):
  File "C:\Users\18776\Desktop\毕业设计\源代码\index.py", line 2, in <module>
    from window.mainimagewin import *
  File "C:\Users\18776\Desktop\毕业设计\源代码\window\mainimagewin.py", line 9, in <module>
    from MVGigE import *
  File "C:\Users\18776\Desktop\毕业设计\源代码\MVGigE.py", line 3, in <module>
    MVGigE = windll.LoadLibrary('MVGigE')
  File "E:\python\lib\ctypes\__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "E:\python\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'MVGigE' (or one of its dependencies). Try using the full path with constructor syntax.

**Comment by ydy2021** [comment]
> 

导包啊

**Comment by aaronrgqw** [comment]
这包MVGigE怎么下载这模块到pycharm

**Comment by aaronrgqw** [comment]
能否交流下

**Comment by aaronrgqw** [comment]
可以加个联系方式交流下吗

**Comment by lazykoalazzz** [comment]
无法打开相机问题，我是自己安装有两个普通RGB相机，请问怎么设置才能用啊，请大佬赐教！

> 我无法打开相机，提示没有找到相机，请确认连接和相机IP设置，怎么设置呢？

你弄成功了吗
